# config.yaml
# 全局配置
global:
  log_level: INFO
  max_workers: 10
  request_delay: [0.5, 1.5]

# 请求器配置
fetcher:
  max_retries: 5
  timeout: 15
  verify_ssl: true
  user_agent_rotation: true

# 存储配置
storage:
  output_dir: "./output"
  formats: [csv, json, parquet]
  raw_storage: true
  exclude_fields: ["raw_html", "temp_data"]

# 中间件配置
middlewares:
  proxies:
    - "http://proxy1.example.com:8080"
    - "http://proxy2.example.com:8080"
  user_agents:
    enabled: true
    custom_agents:
      - "Mozilla/5.0 (Custom Agent 1)"
      - "Mozilla/5.0 (Custom Agent 2)"

# 爬虫专用配置
spiders:
  cnn:
    start_urls:
      - "https://edition.cnn.com/world"
      - "https://edition.cnn.com/politics"
    allowed_domains: ["cnn.com"]
    max_depth: 3

  novel:
    start_urls: ["https://www.qidian.com"]
    allowed_domains: ["qidian.com"]
    item_per_page: 100
